"""
Django settings for pyperfweb project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load PyPerf configuration and display config file info (only once)
_config_displayed = getattr(sys.modules[__name__], '_config_displayed', False)

try:
    # Import PyPerf config from the installed package
    from py_perf.config import get_config
    
    # Load PyPerf configuration
    pyperf_config = get_config()
    
    # Display configuration file information (only once)
    if not _config_displayed:
        print("\n" + "="*60)
        print("🔧 PYPERFWEB SERVER CONFIGURATION")
        print("="*60)
        
        # Show which config file was used
        config_files_checked = [
            Path.cwd() / "py-perf.yaml",
            Path.cwd() / ".py-perf.yaml",
            Path.home() / ".py-perf.yaml",
            Path.home() / ".config" / "py-perf" / "config.yaml"
        ]
        
        active_config_file = None
        for config_file in config_files_checked:
            if config_file.exists():
                active_config_file = config_file
                break
        
        if active_config_file:
            print(f"📄 Using config file: {active_config_file}")
        else:
            print("📄 Using default configuration (no config file found)")
        
        # Show key configuration values
        print(f"🔹 PyPerf enabled: {pyperf_config.is_enabled()}")
        print(f"🔹 Debug mode: {pyperf_config.is_debug()}")
        print(f"🔹 Storage mode: {'Local' if pyperf_config.is_local_only() else 'AWS DynamoDB'}")
        
        if pyperf_config.is_local_only():
            print(f"🔹 Local data dir: {pyperf_config.get('local.data_dir', './perf_data')}")
        else:
            aws_config = pyperf_config.get_aws_config()
            print(f"🔹 AWS region: {aws_config.get('region', 'not set')}")
            print(f"🔹 DynamoDB table: {aws_config.get('table_name', 'not set')}")
        
        # Show dashboard configuration
        dashboard_config = pyperf_config.get_dashboard_config()
        dashboard_host = dashboard_config.get('host', '127.0.0.1')
        dashboard_port = dashboard_config.get('port', 8000)
        print(f"🔹 Dashboard URL: http://{dashboard_host}:{dashboard_port}")
        
        print("="*60)
       
        
        # Mark that we've displayed the config
        sys.modules[__name__]._config_displayed = True
    
    # Store config for use in Django settings
    PYPERFWEB_CONFIG = pyperf_config
    
except Exception as e:
    print(f"\n⚠️  Warning: Could not load PyPerf configuration: {e}")
    print("🔹 Using default Django settings")
    PYPERFWEB_CONFIG = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8-*!p)ez*w2v-uic4chdd$86_6*1ni=f8g*e2efs=ot+561c*$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'pyperfweb.dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pyperfweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pyperfweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AWS DynamoDB Configuration
# Use PyPerf configuration if available, otherwise fall back to environment variables
if 'PYPERFWEB_CONFIG' in locals() and PYPERFWEB_CONFIG:
    aws_config = PYPERFWEB_CONFIG.get_aws_config()
    AWS_DEFAULT_REGION = aws_config.get('region', 'us-east-1')
    DYNAMODB_TABLE_NAME = aws_config.get('table_name', 'py-perf-data')
else:
    # Fallback to environment variables
    AWS_DEFAULT_REGION = os.environ.get('AWS_DEFAULT_REGION', 'us-east-1')
    DYNAMODB_TABLE_NAME = 'py-perf-data'

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.backends.DjangoFilterBackend'],
}
